# Generated by Django 4.2.5 on 2023-09-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data_entrega', models.DateField()),
                ('progresso_atual', models.CharField(max_length=100)),
                ('progresso_necessario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('API', 'API'), ('Cert', 'Certificados'), ('Other', 'Outro')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TarefaRegulatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(max_length=500)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_datas_regulatorias.atividade')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_datas_regulatorias.informe')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_datas_regulatorias.produto')),
            ],
        ),
    ]
