# Generated by Django 4.2.5 on 2023-10-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_datas_regulatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='informe',
            options={'verbose_name': 'Informe', 'verbose_name_plural': 'Informes'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='tarefaregulatoria',
            options={'verbose_name': 'Tarefa Regulatoria', 'verbose_name_plural': 'Tarefa Regulatorias'},
        ),
    ]
