# Generated by Django 4.2.5 on 2023-10-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_datas_regulatorias', '0002_alter_atividade_options_alter_informe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaregulatoria',
            name='titulo',
            field=models.CharField(default=' ', max_length=25),
        ),
        migrations.AlterField(
            model_name='tarefaregulatoria',
            name='escopo',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
