# Generated by Django 4.2.5 on 2023-10-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_datas_regulatorias', '0003_tarefaregulatoria_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('Em Progresso', 'Em Progresso'), ('TODO', 'TODO'), ('Atrasado', 'Atrasado'), ('Concluido', 'Concluido')], default='TODO', max_length=20),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='progresso_atual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='progresso_necessario',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
