# Generated by Django 4.2.5 on 2023-10-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_datas_regulatorias', '0005_alter_atividade_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='status',
        ),
    ]
