# Generated by Django 4.2.5 on 2023-11-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_datas_regulatorias', '0006_remove_atividade_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefaregulatoria',
            name='atividade',
        ),
        migrations.AddField(
            model_name='tarefaregulatoria',
            name='atividade',
            field=models.ManyToManyField(to='app_datas_regulatorias.atividade'),
        ),
    ]
